### ISSUE TITLE
Жирний шрифт скасовується після вставки посилання

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#10]
![image](https://user-images.githubusercontent.com/113423659/190346408-58555955-c2c7-43c2-827f-2e2df60f1a01.png)

**Comment by jmas** [comment]
@maz3pa це той випадок коли ломається текст посилання?

**Comment by maz3pa** [comment]
Воно певно пов'язане одне з одним, але у данному випадку мав на уваці, що шрифт перестає бути жирним після того, як додаєш посилання.

**Comment by jmas** [comment]
@maz3pa Перевір будь ласка як це працює у новому редакторі. Перевідкрий якщо ще актуально.
