### ISSUE TITLE
Cookie файл великого розміру у новій версії сайту

### ISSUE THREAD

**Issue by gamersfan** [uJournal/ujournal-ui#100]
Нова версія сайту створює великі кукі файли, тоді як стара версія цього не робить. 
Чи можливо це виправити?
Розмір можна перевірити тут:
chrome://settings/content/all?searchSubpage=ujournal

**Comment by jmas** [comment]
Привіт, є відповідь у цьому пості: https://ujournal.com.ua/new/post/?postId=3714
Буду працювати над зменшенням кешування PWA версії.
