### ISSUE TITLE
У редагуванні посту зламалися посилання

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#11]
Замість назви гри та посилання ось таке (посилання працює):
![image](https://user-images.githubusercontent.com/113423659/190349518-5cfffbc7-c426-4e9a-ab9c-a36e48184043.png)

**Comment by jmas** [comment]
@maz3pa Можно будьласка текст посилання?

**Comment by maz3pa** [comment]
https://store.steampowered.com/app/1552550/Castlevania_Advance_Collection/?curator_clanid=4777282&utm_source=SteamDB

**Comment by jmas** [comment]
@maz3pa Перевір будь ласка як це працює у новому редакторі. Перевідкрий якщо ще актуально.
