### ISSUE TITLE
+ форматує на позначку списка у коментарях

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#19]
![image](https://user-images.githubusercontent.com/113423659/190851128-0e4900f6-7076-4d58-ba3f-ada329fdc480.png)
![image](https://user-images.githubusercontent.com/113423659/190851138-b45e92aa-bb01-4fbc-b36a-84983c228783.png)

**Comment by jmas** [comment]
@maz3pa так це така поведінка Markdown. Як вважаєш критична?

**Comment by maz3pa** [comment]
@jmas так, люди часто бажають бачити підтримку їх точки зору. Тим паче в нас нема нотифікацій, коли тебе хтось плюсує або мінусить.

**Comment by jmas** [comment]
@maz3pa Зрозумів, треба переробити на спец-символи. Дякую!

**Comment by jmas** [comment]
@maz3pa Додав фікс для того щоб працював `+` у комментах. Перевір будь ласка) Якщо щось не так перевідкрий.
