### ISSUE TITLE
Через стрічку коментарів можна потрапити до видаленого запису

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#20]
![image](https://user-images.githubusercontent.com/113423659/190866493-8b1230a4-8e6a-4fef-8afa-d538e77e31de.png)

**Comment by jmas** [comment]
@maz3pa Додав фікс, тепер видалені пости не відображаються.

**Comment by maz3pa** [comment]
@jmas але через стрічку коментів праворуч все ще можна потрапити до видаленного посту.

**Comment by jmas** [comment]
@maz3pa Будь ласка додай лінк на Пост

**Comment by maz3pa** [comment]
@jmas https://ujournal.com.ua/post/1936
