### ISSUE TITLE
Кнопки профілю та налаштувань не працюють

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#23]
![image](https://user-images.githubusercontent.com/113423659/190892360-584351a5-6959-47ef-b2a8-893bb63f9b6f.png)
![image](https://user-images.githubusercontent.com/113423659/190892368-a7a9b26c-2860-433a-bdcd-cfcae8673f7b.png)

**Comment by jmas** [comment]
@maz3pa тимчасово прибрал. Ішью поки не закриваю. Закрою коли будуть готові розділи.

**Comment by maz3pa** [comment]
Справедливо.джпг

**Comment by jmas** [comment]
Поки закрию ішью щоб не відволікатися.
