### ISSUE TITLE
Переробити Caption до зображення

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#24]
Зробити підпис до зображення знизу самого зображення (як TJ)

![Screenshot_20220918-211446](https://user-images.githubusercontent.com/95772447/190922466-ffba2f2e-07f6-44f8-852f-ce9ae80d62ef.jpg)

![Screenshot_20220918-211452](https://user-images.githubusercontent.com/95772447/190922470-5e1a14ea-e17b-4b1d-afcd-264544039fd7.jpg)

**Comment by jmas** [comment]
@AoHeaven Зроблено.

Як виглядає у рєдакторі:

![](https://user-images.githubusercontent.com/90701/190928721-28b6c2dc-d2cd-4b39-9292-d008a5cf8ba4.png)

Як виглядає у пості:
