### ISSUE TITLE
Помилка в правилах. ujouNRal.com.ua/new/legal замість ujouRNal.com.ua/new/legal

### ISSUE THREAD

**Issue by maxduh** [uJournal/ujournal-ui#26]
![[ujounral.com.ua/new/legal](https://ujounral.com.ua/new/legal/)](https://user-images.githubusercontent.com/37228674/190923033-b660ec3f-8ff0-41d5-8538-cb24d4fc599f.png)

**Comment by jmas** [comment]
@maxduh Пофіксив, дяка!
