### ISSUE TITLE
Замінити сортування "Hot" на "Top Day" в розділі "Популярні"

### ISSUE THREAD

**Issue by maxduh** [uJournal/ujournal-ui#27]
"Hot" якось дивно працює

**Comment by jmas** [comment]
@maxduh  У старій версії за замовченням стоїть "Активні". Може спробувати Активні, як вважаєш?

**Comment by maxduh** [comment]
Активні вже є

**Comment by jmas** [comment]
@maxduh Додав, перевір будь ласка: https://ujournal.com.ua/new/?type=All&sort=TopDay&page=1&limit=20
<img width="221" alt="Знімок екрана 2022-09-19 о 16 01 54" src="https://user-images.githubusercontent.com/90701/191023285-e5df3aa7-a496-490e-a666-70462cfdb129.png">
