### ISSUE TITLE
(Android) Caption вилазить за сторінку

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#28]
![Screenshot_20220919-003815](https://user-images.githubusercontent.com/95772447/190929072-bfd27820-0dc8-47a3-8c35-804cf1a0eb8d.jpg)

![Screenshot_20220919-004008__01](https://user-images.githubusercontent.com/95772447/190929129-218e7b50-359c-4201-ad6e-56026d6c0c50.jpg)

**Comment by jmas** [comment]
@AoHeaven Повинно бути пофікшено. Чекни пліз.

**Comment by AoHeaven** [comment]
> @AoHeaven Повинно бути пофікшено. Чекни пліз.

Так, виправлено.
![Screenshot_20220919-010055](https://user-images.githubusercontent.com/95772447/190929706-a7464d1f-fd81-45c5-87b0-40d67c3f44ba.jpg)
