### ISSUE TITLE
Створення поста. Не працює додавання картинок

### ISSUE THREAD

**Issue by jmas** [uJournal/ujournal-ui#29]
Якщо в тілі поста завантажити картинку та не редагувати тіло, то картинка не зберігається

**Comment by maz3pa** [comment]
@jmas зображення також перестали вантажитися у коментарях.

**Comment by jmas** [comment]
Поки що не знайшов гарного рішення. Може хтось порадить де знайти нормальний хостінг для графіки щоб туди можно було картинки грузити по API напряму без серверного апі (додатково булоб класно якщо б був ресайз).

**Comment by jmas** [comment]
Зараз працює. Поки закриваю
