### ISSUE TITLE
Картка спільноти вилізає за сторінку

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#30]
![image](https://user-images.githubusercontent.com/95772447/190998041-7dde6bc0-57c0-4628-acca-c4f8277cb6d0.png)
![image](https://user-images.githubusercontent.com/95772447/190998217-fe1f679a-9ffc-44d7-968c-9f1b8c46cfe1.png)

**Comment by jmas** [comment]
@AoHeaven Fixed:
<img width="1512" alt="Знімок екрана 2022-09-19 о 16 02 55" src="https://user-images.githubusercontent.com/90701/191023428-a04f2c6d-2925-4daa-817e-da740aef01be.png">
