### ISSUE TITLE
Переробити список спільнот на панелі зліва

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#31]
На даний момент список спільнот на панелі зліва дублюється зі спільнотами, розташованими при переході натиском кнопки "Спільноти".
![Screenshot_20220919-212747](https://user-images.githubusercontent.com/95772447/191089759-8bb0d86d-97df-475f-b642-71194dce2125.jpg)
Пропоную список усіх спільнот замінити на список спільнот, на які підписаний користувач
![Screenshot_20220919-212414](https://user-images.githubusercontent.com/95772447/191089944-84f8e2c8-c4c3-4eb3-8e01-6d4f8767ba5e.jpg)

**Comment by jmas** [comment]
@AoHeaven зараз зроблено два списка:

*   10 спільнот на які підписан користувач
*   10 топ-спільнот мінус спільноти на які підписан користувач

**Comment by AoHeaven** [comment]
Дякую
