### ISSUE TITLE
Помилка при відкритті профілю користувача

### ISSUE THREAD

**Issue by aelmod** [uJournal/ujournal-ui#33]
### Issue Summary

Safari iOS 16
Помилка при відкритті профілю користувача:
**Application error: a client-side exception has occurred (see the browser console for more information).**
Відео: https://share.icloud.com/photos/058BH2mIT3N4sz_vWfF_1EE7g

### Steps to Reproduce

Відкрити сторінку любого користувача

### Technical details

Помилки з консолі:
```
Start Date is invalid

A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Start Date is invalid

Start Date is invalid

A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by jmas** [comment]
@aelmod Додай будь ласка лінк на Юзера. Дякую!

**Comment by aelmod** [comment]
Це відтворюється коли відкриваєш профіль любого користувача. Чи ти маєш на увазі мого юзера?

**Comment by jmas** [comment]
@aelmod Якщо можно твого юзера і всеж таки лінк на профіль юзера якого дивишся.

**Comment by aelmod** [comment]
@jmas мій профіль: https://ujournal.com.ua/new/user/?userId=22
Кого дивився: https://ujournal.com.ua/new/user/?userId=2

**Comment by aelmod** [comment]
@jmas з компа та ж сама історія, коли відкриваєш профіль і натискаєш F5. Тоді довго грузить цифри, але з часом прогружає і в консолі отаке: 
![image](https://user-images.githubusercontent.com/9832072/191328524-3b8cd1a3-ccbc-417b-96e8-b9057ad2528e.png)

**Comment by aelmod** [comment]
@jmas можливо проблема в не правильних id в запиті
![image](https://user-images.githubusercontent.com/9832072/191329178-7ab03bbc-bbad-4ae6-9f08-c0c349230d45.png)

**Comment by jmas** [comment]
@aelmod так додав фікс, прибрав помилкову ID -1. Перевір будь ласка. Довго грузить бо чомусь запити на юзера довго обробляє.

**Comment by aelmod** [comment]
@jmas запити пофіксились, але проблема залишилась. Тепер можна відкрити профіль користувача з додатку, але коли відкриваєш і оновлюєш сторінку, то та ж сама проблема 
![image](https://user-images.githubusercontent.com/9832072/191333109-6e573d9f-0c5c-4b8f-8a0d-4662a510da56.png)

https://reactjs.org/docs/error-decoder.html?invariant=423
https://reactjs.org/docs/error-decoder.html?invariant=425

**Comment by jmas** [comment]
@aelmod зрозумів, буду дивитись як пофіксити помилки у консолі. Якщо профіль відкривається - закриваю багу. Перевідкрий якщо інтерфейс буде крашитись знову. Дякую.

**Comment by aelmod** [comment]
Профіль відкривається не в усіх випадках. Коли відкриваєш профіль як нову сторінку чи перезавантажуєш, то проблема залишається
https://user-images.githubusercontent.com/9832072/191335160-e024a58d-eb32-4c09-95b3-0bc8ffd1ca4f.MOV

**Comment by jmas** [comment]
@aelmod дякую, закинув фікс, перевір будь ласка.

**Comment by aelmod** [comment]
@jmas тепер все віркає як треба. Дякую
