### ISSUE TITLE
(Desktop) Баг при наведенні на автора в пості

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#34]
![image](https://user-images.githubusercontent.com/95772447/191196460-df23ab4b-2c9c-40c3-a6f4-ffc19776e648.png)

**Comment by jmas** [comment]
@AoHeaven Будь ласка лінк на пост додай.

**Comment by jmas** [comment]
@AoHeaven пофікшено. Перевір будь ласка.

**Comment by AoHeaven** [comment]
Виправлено, але посилання тепер не відрізнити від тексту
![image](https://user-images.githubusercontent.com/95772447/191324747-51de831d-0c1c-4c2a-b5ef-7b82ccd8f432.png)
