### ISSUE TITLE
В стрічні дублюються пости

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#35]
Іноді при перегляді стрічки можна натрапити на продубльовані пости
![image](https://user-images.githubusercontent.com/95772447/191223783-5e9f0118-7751-4187-88b0-560739f60856.png)
Вони нічим не відрізняються, тільки показуються 2 рази, один за одним

**Comment by jmas** [comment]
@AoHeaven Додав фікс для цього. Вже десь тиждень праціює. Перевіряється за лінком. Перевір будь ласка, перевідкрий якщо актуально.
