### ISSUE TITLE
Щось с підписом у коментарях

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#37]
![image](https://user-images.githubusercontent.com/113423659/191245656-ed2861bf-c865-43c8-a430-323cc6c84f12.png)
![image](https://user-images.githubusercontent.com/113423659/191245706-72432ec4-5936-42fe-b88d-1469a3c81a71.png)

**Comment by maz3pa** [comment]
https://ujournal.com.ua/new/post/?postId=1699#comments

**Comment by jmas** [comment]
@maz3pa fixed, перевір будь ласка.

**Comment by maz3pa** [comment]
Працює.
