### ISSUE TITLE
Перенесення до коментарів прямо зі стрічки працює не коректно

### ISSUE THREAD

**Issue by Hrestonosec** [uJournal/ujournal-ui#38]
При натисканні в стрічці “Коментарі”, то видно що спочатку сторінка знаходиться там де треба (буквально півсекунди), а коли вона підвантажується повністю, то закидає на початок посту. Адреса наче прописана коректно

![image](https://user-images.githubusercontent.com/58342195/191336449-4508fe48-a3dc-4cab-abaf-14cae7ffd0b2.png)

Браузер Chrome

**Comment by jmas** [comment]
@Hrestonosec пофіксив, перевір будь ласка. Якщо ще актуально - перевідкрий тікет. Дякую!

**Comment by Hrestonosec** [comment]
Так, все тепер працює. Дуже дякую за оперативність
