### ISSUE TITLE
Пропозиція прибрати кнопку "Нові коментарі"

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#43]
Тому що:
1) Вона дублює стрічку коментарів праворуч;
2) Ця кнопка частково дублює кнопку "Обговорюване";
1) Кнопок ліворуч дуже багато.

**Comment by jmas** [comment]
@maz3pa Привіт, вирішив згрупувати кнопки і сховати в меню другого рівня.

<img width="262" alt="Знімок екрана 2022-09-23 о 21 29 25" src="https://user-images.githubusercontent.com/90701/192033608-500c4e59-0669-4f75-b2f6-64899727aa7a.png">

**Comment by maz3pa** [comment]
@jmas, цікава ідея. Я б топ залишив, мені здається популярна кнопка - зайти увечері та подивитись, що там за день було популярного. А нема статистики, які кнопки частіше клацають? Може опитування провести. Я за весь час користувався новим та топом.
Активні пов'язано з коментуванням? Якщо так, то може в ньому сховати Обговорюване та Нові коментарі?
