### ISSUE TITLE
Додати в заголовок сторінки назву поста (при перегляді)

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#46]
![image](https://user-images.githubusercontent.com/95772447/192113871-aa09a4ca-3023-4c03-8985-00fd9b0173fe.png)
![image](https://user-images.githubusercontent.com/95772447/192113923-4c78d2d3-c92d-4968-aed9-3d33d79340ce.png)

**Comment by ujournal-tester** [comment]
@AoHeaven Додав тайтл, перевір будь ласка.

**Comment by jmas** [comment]
@AoHeaven додав тайтл, перевір будь ласка.

**Comment by AoHeaven** [comment]
> @AoHeaven додав тайтл, перевір будь ласка.

Працює, дякую 👍
![Screenshot_20220924-223653](https://user-images.githubusercontent.com/95772447/192115602-a9ac5202-dee2-4b40-801a-985ab7374660.jpg)

**Comment by jmas** [comment]
@AoHeaven у нас зʼявився телеграм канал: https://t.me/ujournal_posts

**Comment by AoHeaven** [comment]
> @AoHeaven у нас зʼявився телеграм канал: https://t.me/ujournal_posts

Добре
