### ISSUE TITLE
(Android, iOS) Відсутні пункти лівої та правої панелей при створенні поста

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#47]
При створенні поста ліва та права панелі пусті, тобто пункти в них відсутні. Можливо це через те, що в Desktop версії їх теж немає, відсутня сама кнопка меню.
![Screenshot_20220924-230749](https://user-images.githubusercontent.com/95772447/192116614-6efd8939-f6c3-477d-a962-7c6c4b8e3756.jpg)
![Screenshot_20220924-230755](https://user-images.githubusercontent.com/95772447/192116634-28392321-d425-4790-9394-0f45a761c6e4.jpg)
В мене є пропозиція вирішити цю проблему двома варіантами.
Перший варіант - ми додаємо відсутні пункти в ліву та праву панелі на Android та iOS.
Другий варіант - ми прибираємо кнопку меню при створенні поста на Android та iOS, так само, як і на Desktop.

**Comment by jmas** [comment]
@AoHeaven підправив. Зараз там буде відображатися меню і правила. Якщо є зауваження перевідкрий будь ласка.

**Comment by AoHeaven** [comment]
> @AoHeaven підправив. Зараз там буде відображатися меню і правила. Якщо є зауваження перевідкрий будь ласка.

Чудово, класно зроблено. Дякую 👍
![Screenshot_20220926-234555](https://user-images.githubusercontent.com/95772447/192377273-3c7cc38c-5584-4f44-bc44-e074fda542ce.jpg)
![Screenshot_20220926-234600](https://user-images.githubusercontent.com/95772447/192377297-fefe0c1f-c911-4a32-ae6f-b320bd12506e.jpg)
