### ISSUE TITLE
(Android, iOS) Відсутні пункти в лівій та правій панелях при перегляді профілю

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#48]
![Screenshot_20220924-233226](https://user-images.githubusercontent.com/95772447/192117922-e0bc4671-0108-4e5e-974e-78b33b42d291.jpg)
![Screenshot_20220924-233232](https://user-images.githubusercontent.com/95772447/192117925-c7a3b045-ce12-4a1a-95a3-a213a2762864.jpg)
![Screenshot_20220924-233237](https://user-images.githubusercontent.com/95772447/192117928-68ca269d-8b53-479d-a64c-135c823d4f4b.jpg)

**Comment by jmas** [comment]
@AoHeaven Додав ліву панель, права панел буде відсудня у режимі перегляду сторінки юзера. Мабуть я буду скривати іконку правої панелі у бургєр-меню при її відсутності.
