### ISSUE TITLE
Кривой импорт с реддита

### ISSUE THREAD

**Issue by ohshie** [uJournal/ujournal-ui#49]
### Issue Summary

Едет верстка при вставке блока с реддита

https://i.postimg.cc/fTvCw22v/Screenshot-2022-09-25-at-12-03-52.png
### Steps to Reproduce

1. создать пост с реддита
2. увидеть что все поехало

### Technical details

* What OS / Browser are you using? 
максо, фаерфокс

**Comment by jmas** [comment]
@ohshie Підкажи будь ласка, висота посту некоректна?

**Comment by ohshie** [comment]
не, там получается что текст заголовка занимает весь "белый блок", который отведен на пост, а изображение не масштабируется под размер текста из-за чего получается что снизу пустое место.
<img width="823" alt="Screenshot 2022-09-27 at 10 49 30" src="https://user-images.githubusercontent.com/114024290/192453662-a8a1fc81-24e8-4764-b087-06613d8e5c55.png">
Плюс по сравнению с другими постами выглядит странно
<img width="811" alt="Screenshot 2022-09-27 at 10 50 05" src="https://user-images.githubusercontent.com/114024290/192453757-934a467f-a38f-4d70-9076-21aab6f385fc.png">

у них есть поля, а при вставки с реддита нет полей

**Comment by jmas** [comment]
@ohshie Підправив, тепер пости з Редіта виглядають як треба: 
<img width="706" alt="Знімок екрана 2022-09-27 о 14 30 45" src="https://user-images.githubusercontent.com/90701/192514082-32bd4550-1f7c-40e0-84f5-342c480961c8.png">
перевір будь-ласка. Якщо є проблеми - перевідкрий)
