### ISSUE TITLE
Прибрати горизонтальні полоси зверху і знизу зображення в пості

### ISSUE THREAD

**Issue by ItsCrea** [uJournal/ujournal-ui#51]
Як на мене, вони зайві і займають занадто багато місця в стрічці.

![image](https://user-images.githubusercontent.com/114384930/192211855-fb7cc418-ad37-4c56-aa30-4ccadf3dbbf3.png)

**Comment by maz3pa** [comment]
@ItsCrea це іш'ю #9, воно вже існує.

**Comment by jmas** [comment]
@ItsCrea Привіт, перевір будь ласка. Додав фікс. Якщо є зауваження - перевідкрий.
