### ISSUE TITLE
Наприкінці посту неможливо додати текст після вставки з ютуб

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#52]
Між "Створити" та плеєром нема місця для тексту:
![image](https://user-images.githubusercontent.com/113423659/192234681-b2c3304a-1ee4-4c5f-81da-a1517cdd6a49.png)

**Comment by jmas** [comment]
@maz3pa Дякую за повідомлення. Зараз можно додавати через "+". Я думаю треба завжди додавати зайве поле для тексту після вставки ембедів.

**Comment by jmas** [comment]
@maz3pa Поки закриваю ішью, бо це стосувалося EditorJS. Якщо після додавання можливості вставки медіа у новий редактор буде теж сама проблема - перевідкриемо, гаразд? Бо хочу прибрати не дуже актуальні ішью. Дякую тобі!
