### ISSUE TITLE
Закладки ЗАКЛАДКИ з_а_к_л_а_д_к_и !

### ISSUE THREAD

**Issue by Richex** [uJournal/ujournal-ui#54]
З А К Л А Д К И
А
К
Л
А
Д
К
И
![ЗАКЛАДКИ](https://user-images.githubusercontent.com/800060/192812489-5bcef466-dd11-4d44-bbbc-aa51c3bb41c4.jpg)
з.а.к.л.а.д.к.и.

**Comment by jmas** [comment]
@Richex ❤️️🤘

**Comment by jmas** [comment]
@Richex привіт, додав "Збережене", це тіж самі закладки. Докладно у цьому оновленні: https://ujournal.com.ua/new/post/?postId=3202 Якщо є додаткові питання, зведи будь ласка нову ішью. Дякую!
