### ISSUE TITLE
Лічильник дати реєстрації починає відлік спочатку

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#55]
Лічильник дати реєстрації починає відлік з 0 після досягнення місяця з дати реєстрації.
![Screenshot_20220928-232724](https://user-images.githubusercontent.com/95772447/192882409-38704419-d55a-4b7f-ab64-f1e2b6cd02a1.jpg)

**Comment by jmas** [comment]
@AoHeaven Додав фікс, перевір будь ласка, якшо не праціює перевідкрий:

![](https://user-images.githubusercontent.com/90701/192901331-50d5db53-5ea4-45b4-8cbe-709386b75b4e.png)

**Comment by AoHeaven** [comment]
> @AoHeaven Додав фікс, перевір будь ласка, якшо не праціює перевідкрий:
> 
> ![](https://user-images.githubusercontent.com/90701/192901331-50d5db53-5ea4-45b4-8cbe-709386b75b4e.png)

Працює, дякую
![Screenshot_20220929-090638](https://user-images.githubusercontent.com/95772447/192952213-52516c3f-0bc4-4adf-af38-2cc24f15dae6.jpg)
