### ISSUE TITLE
Якщо редагувати пост зникають текст та посилання

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#63]
![image](https://user-images.githubusercontent.com/113423659/193024775-f7aaaa51-4945-421d-a797-37ac4bbd7e8d.png)
![image](https://user-images.githubusercontent.com/113423659/193024735-5de8f8e2-3a3d-4e70-9bab-7df8107befb2.png)

лінк: https://ujournal.com.ua/new/post/?postId=2618#comments

**Comment by jmas** [comment]
@maz3pa Після зміни редактора проблема все ще актуальна. Перевір будь ласка. Якщо все ще актуальна - перевідкрий.
