### ISSUE TITLE
Додати плейсхолдер для картинок що не завантажилися

### ISSUE THREAD

**Issue by ujournal-tester** [uJournal/ujournal-ui#68]
Картинки що не завантажилися повинні мати плейсхолдер (якийсь текст типу "відкрити зображення у новому вікні"). Бо статі наприклад ця https://ujournal.com.ua/new/post/?postId=2998 мають зображення з ішного сайту, які не відображаються. Треба зробити так щоб люди могли їх відкривати за посиланням.

**Comment by jmas** [comment]
Додав.
