### ISSUE TITLE
Оновлювати зміст, під час переключання кнопок "Нове", "Популярне" та ін.

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#69]
Зараз контент не оновлюється, та показує ті пости, що були на момент входу на сайт, для їх оновлення треба кожного разу жати ф5.

![image](https://user-images.githubusercontent.com/113423659/193591815-625f7b0c-5103-4648-b9f1-88ae37c93d50.png)

**Comment by jmas** [comment]
@maz3pa Додав покращення. Перевір будь ласка. Перевідкрий якщо є зауваження. Дякую!

**Comment by belenkiyua** [comment]
Бачу що я відкривав похожу проблему,
нажаль для мене не працює як я очікував
детально описав у своєму тікеті https://github.com/uJournal/ujournal-ui/issues/74
