### ISSUE TITLE
Delete own messages / Видалення своїх повідомлень

### ISSUE THREAD

**Issue by belenkiyua** [uJournal/ujournal-ui#70]
Чекаємо на можливість видалення своїх повідомлень для юзерів,
Важлива функція коли помилкові коментарі пишуться, або треба перевзутися у повітрі)

**Comment by jmas** [comment]
@belenkiyua Привіт, додав можливість видаляти коментарі, перевір будь ласка. Якщо є коментарі - перевідкрий будь ласка.

![](https://user-images.githubusercontent.com/90701/194388101-42e8d42b-cce1-4061-9325-3da278da33c8.png)
