### ISSUE TITLE
Додати можливість робити різну кількість embed контенту у тілі поста.

### ISSUE THREAD

**Issue by DmitryJDS** [uJournal/ujournal-ui#8]
Приклад:
<img width="803" alt="Screenshot_6" src="https://user-images.githubusercontent.com/18308591/189977210-e63b754c-ab3c-44ea-87b9-a1896290ff67.png">
Було б гарно мати можливість додавати декілька embed відео до одного поста.

**Comment by jmas** [comment]
@DmitryJDS поки додав можливість додавати YouTube відео до тіла поста через кнопку:

![](https://user-images.githubusercontent.com/90701/190928916-dfe06c65-51f6-49eb-843a-16415f519402.png)

Планую доробити рєдактор щоб він вмів показувати різні ембеди. Поки вчуся робити екстеншени до редактора, згодом буду робити спеціальний екстеншн який буде працюавти по принципу поля URL. Поки ішью не закриваю.
