### ISSUE TITLE
Зрада у тегах

### ISSUE THREAD

**Issue by maz3pa** [uJournal/ujournal-ui#91]
Неактивні:

![image](https://user-images.githubusercontent.com/113423659/194282236-a8adfaff-352b-4b77-b6db-f9f7816e4256.png)

**Comment by jmas** [comment]
@maz3pa тег повинен складатися з декількох символів, мінімум з двох літер. Перевір ще раз будь ласка.

**Comment by jmas** [comment]
@maz3pa перевір, додав підтримку усіх символів:
<img width="496" alt="Screenshot 2022-10-06 at 18 43 30" src="https://user-images.githubusercontent.com/90701/194358162-9f415501-e927-4104-8df1-5b9ca9336a8c.png">
Якщо є проблеми перевідкрий будь ласка.
