### ISSUE TITLE
(Mobile) Чорний текст на темному фоні в профілі

### ISSUE THREAD

**Issue by AoHeaven** [uJournal/ujournal-ui#93]
![Screenshot_20221006-235749__01](https://user-images.githubusercontent.com/95772447/194417718-627b09d1-65d7-498d-bbe2-1a320a36600a.jpg)

**Comment by jmas** [comment]
@AoHeaven Пофіксив, дякую! 

![](https://user-images.githubusercontent.com/90701/194419934-2daa5c2a-dfa1-490d-9749-9665ee392873.png)
